### ISSUE TITLE
fatal error: 'bits/c++config.h' file not found

### ISSUE THREAD

**Issue by blowback** [rprichard/sourceweb#2]
On the first step, I get the following error:

```
ajs4@ajs4ld:~/Packages/SourceWeb/sourceweb$ ./configure --with-clang-dir=/home/ajs4/Packages/SourceWeb/sourceweb-clang
Looking for qmake...
- which qmake-qt4
- found /usr/bin/qmake-qt4
Testing C++11 support using /usr/bin/qmake-qt4...
- running: /home/ajs4/Packages/SourceWeb/sourceweb/cxx11-compat-test/run-test.sh /usr/bin/qmake-qt4 QMAKE_CC=/home/ajs4/Packages/SourceWeb/sourceweb-clang/bin/clang QMAKE_CXX=/home/ajs4/Packages/SourceWeb/sourceweb-clang/bin/clang++ QMAKE_LINK=/home/ajs4/Packages/SourceWeb/sourceweb-clang/bin/clang++
- Command failed.  Output of /home/ajs4/Packages/SourceWeb/sourceweb/cxx11-compat-test.log:
    + mkdir cxx11-compat-test-build
    + cd cxx11-compat-test-build
    + /usr/bin/qmake-qt4 QMAKE_CC=/home/ajs4/Packages/SourceWeb/sourceweb-clang/bin/clang QMAKE_CXX=/home/ajs4/Packages/SourceWeb/sourceweb-clang/bin/clang++ QMAKE_LINK=/home/ajs4/Packages/SourceWeb/sourceweb-clang/bin/clang++ /home/ajs4/Packages/SourceWeb/sourceweb/cxx11-compat-test/cxx11-compat-test.pro
    + make
    /home/ajs4/Packages/SourceWeb/sourceweb-clang/bin/clang++ -c -m64 -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -I/usr/share/qt4/mkspecs/linux-g++-64 -I../cxx11-compat-test -I/usr/include/qt4 -I. -I../cxx11-compat-test -I. -o main.o ../cxx11-compat-test/main.cc
    In file included from ../cxx11-compat-test/main.cc:11:
    In file included from /usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/4.7/algorithm:60:
    /usr/lib/gcc/x86_64-linux-gnu/4.7/../../../../include/c++/4.7/utility:69:10: fatal error: 'bits/c++config.h' file not found
    #include <bits/c++config.h>
    ^
    1 error generated.
    make: *** [main.o] Error 1
```

**Comment by rprichard** [comment]
I've updated SourceWeb (with help from @adytzu2007) to use Clang 3.5 instead of Clang 3.2.  As of the update, the project no longer concerns itself with providing a host C++11 compiler or libraries, or (currently) with providing prebuilt Clang binaries.  The `configure` script still tests the host compiler for C++11 support.

I'm hoping this won't be too much of an inconvenience.  Linux distributions updated in the past few years (e.g. Ubuntu 12.04 and later) have good enough C++11 support.  Getting Clang 3.5 binaries could be harder, but:
 - Ubuntu 14.04 has a `libclang-3.5-dev` package.  I updated the `configure` script to look for this at `/usr/lib/llvm-3.5`.  I updated the `README.md` to list this package.
 - There are prebuilt packages from llvm.org for OS X and some Linux distributions.  The Linux support for 3.5 is limited to Fedora 20, Ubuntu 14.04 and OpenSUSE 13.1.
 - While building LLVM+Clang is time-consuming, it's fairly straightforward.
 - Conceivably, I could change the build system to download and build LLVM automatically.

Anyway, I've tested the current version on Linux and OS X (Ubuntu 14.04, Fedora 20, OS X 10.10), and it doesn't have this `bits/c++config.h` bug anymore.
